// ================================================================
// TestCase Studio — Playwright Script
// Name  : VYNS DELIGHTS Tests 11
// Date  : 08/07/2026 16:04:28
// Steps : 65
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node VYNS_DELIGHTS_Tests_11.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 65 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('https://vyns.elshaseries.com/admin');

  // Step 2: Click on "Admin"
  // Playwright: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(4) > div:nth-child(1) > a:nth-child(1)')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@aria-label=\'Admin\']//a[@class=\'p-menuitem-link\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(4) > div:nth-child(1) > a:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[6]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Admin\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Admin"');
  await el_2.click();

  // Step 3: Click on "Commandes"
  // Playwright: page.locator('a[href=\'/admin/commandes\']')
  const el_3 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Commandes\']') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'/admin/commandes\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[9]') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(3)') }
  ], 'Click on "Commandes"');
  await el_3.click();

  // Step 4: Click on "Statut"
  // Playwright: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(3) > td:nth-child(7) > button:nth-child(1)')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tr[@draggable=\'false\']//button[@aria-label=\'Statut\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(3) > td:nth-child(7) > button:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[8]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Statut\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Statut"');
  await el_4.click();

  // Step 5: Click on "svgElement"
  // Playwright: page.locator('.p-icon.p-dropdown-trigger-icon.p-clickable')
  const el_5 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//*[@class=\'p-icon p-dropdown-trigger-icon p-clickable\']') },
    { label: 'CSS (primary)', loc: page.locator('.p-icon.p-dropdown-trigger-icon.p-clickable') }
  ], 'Click on "svgElement"');
  await el_5.click();

  // Step 6: Click on "Livrée"
  // Playwright: page.locator('#dropdownItem_3')
  const el_6 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@id=\'dropdownItem_3\']') },
    { label: 'CSS (primary)', loc: page.locator('#dropdownItem_3') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//li)[22]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//li[normalize-space()=\'Livrée\']') },
    { label: 'nth-of-type CSS', loc: page.locator('li:nth-of-type(4)') }
  ], 'Click on "Livrée"');
  await el_6.click();

  // Step 7: Click on "Enregistrer"
  // Playwright: page.locator('button[aria-label=\'Enregistrer\']')
  const el_7 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Enregistrer\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Enregistrer\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[42]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Enregistrer\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Enregistrer"');
  await el_7.click();

  // Step 8: Click on "Statut"
  // Playwright: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(7) > button:nth-child(1)')
  const el_8 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tbody/tr[1]/td[1]/button[1]') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(7) > button:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[13]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Statut\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Statut"');
  await el_8.click();

  // Step 9: Click on "Annuler"
  // Playwright: page.locator('button[aria-label=\'Annuler\']')
  const el_9 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Annuler\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Annuler\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[41]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Annuler\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Annuler"');
  await el_9.click();

  // Step 10: Click on "Statut"
  // Playwright: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(7) > button:nth-child(1)')
  const el_10 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tbody/tr[1]/td[1]/button[1]') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(7) > button:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[12]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Statut\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Statut"');
  await el_10.click();

  // Step 11: Click on "svgElement"
  // Playwright: page.locator('.p-icon.p-dropdown-trigger-icon.p-clickable')
  const el_11 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//*[@class=\'p-icon p-dropdown-trigger-icon p-clickable\']') },
    { label: 'CSS (primary)', loc: page.locator('.p-icon.p-dropdown-trigger-icon.p-clickable') }
  ], 'Click on "svgElement"');
  await el_11.click();

  // Step 12: Click on "Annulée"
  // Playwright: page.locator('#dropdownItem_4')
  const el_12 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@id=\'dropdownItem_4\']') },
    { label: 'CSS (primary)', loc: page.locator('#dropdownItem_4') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//li)[23]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//li[normalize-space()=\'Annulée\']') },
    { label: 'nth-of-type CSS', loc: page.locator('li:nth-of-type(5)') }
  ], 'Click on "Annulée"');
  await el_12.click();

  // Step 13: Click on "Enregistrer"
  // Playwright: page.locator('button[aria-label=\'Enregistrer\']')
  const el_13 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Enregistrer\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Enregistrer\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[42]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Enregistrer\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Enregistrer"');
  await el_13.click();

  // Step 14: Click on "Produits"
  // Playwright: page.locator('a[href=\'/admin/produits\']')
  const el_14 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Produits\']') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'/admin/produits\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[8]') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(2)') }
  ], 'Click on "Produits"');
  await el_14.click();

  // Step 15: Click on "Supprimer"
  // Playwright: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(7) > div:nth-child(1) > button:nth-child(2)')
  const el_15 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tr[@draggable=\'false\']//button[@aria-label=\'Supprimer\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(7) > div:nth-child(1) > button:nth-child(2)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[5]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Supprimer"');
  await el_15.click();

  // Step 16: Click on "Supprimer"
  // Playwright: page.locator('.p-button-danger.p-confirm-dialog-accept.p-button.p-component')
  const el_16 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@class=\'p-button-danger p-confirm-dialog-accept p-button p-component\']') },
    { label: 'CSS (primary)', loc: page.locator('.p-button-danger.p-confirm-dialog-accept.p-button.p-component') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[35]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Supprimer\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Supprimer"');
  await el_16.click();

  // Step 17: Scroll down
  // Playwright: page.locator('button[aria-label=\'Supprimer\']')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 18: Click on "Modifier"
  // Playwright: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(6) > td:nth-child(7) > div:nth-child(1) > button:nth-child(1)')
  const el_18 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//tr[@draggable=\'false\']//button[@aria-label=\'Modifier\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(2) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(6) > td:nth-child(7) > div:nth-child(1) > button:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[14]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Modifier"');
  await el_18.click();

  // Step 19: Click on "Stock"
  // Playwright: page.locator('.p-inputnumber-button.p-inputnumber-button-up.p-button.p-button-icon-only.p-component')
  const el_19 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@class=\'p-inputnumber-button p-inputnumber-button-up p-button p-button-icon-only p-component\']') },
    { label: 'CSS (primary)', loc: page.locator('.p-inputnumber-button.p-inputnumber-button-up.p-button.p-button-icon-only.p-component') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[34]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Stock"');
  await el_19.click();

  // Step 20: Click on "Enregistrer"
  // Playwright: page.locator('button[aria-label=\'Enregistrer\']')
  const el_20 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Enregistrer\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Enregistrer\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[37]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Enregistrer\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Enregistrer"');
  await el_20.click();

  // Step 21: Scroll up
  // Playwright: page.locator('button[aria-label=\'Enregistrer\']')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 22: Click on "Accueil"
  // Playwright: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(1) > div:nth-child(1) > a:nth-child(1)')
  const el_22 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@aria-label=\'Accueil\']//a[@class=\'p-menuitem-link\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(1) > div:nth-child(1) > a:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[3]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Accueil\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Accueil"');
  await el_22.click();

  // Step 23: Scroll down
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 24: Click on "Attiéké poisson 30463 FCFAAjouter"
  // Playwright: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(4) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2)')
  const el_24 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//div[@class=\'products-grid\']//div[1]//div[1]') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > main:nth-child(2) > div:nth-child(1) > section:nth-child(4) > div:nth-child(2) > div:nth-child(3) > div:nth-child(2)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//div)[49]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//div[normalize-space()=\'Attiéké poisson 304 63 FCFA Ajouter\']') },
    { label: 'nth-of-type CSS', loc: page.locator('div:nth-of-type(1)') }
  ], 'Click on "Attiéké poisson 30463 FCFAAjouter"');
  await el_24.click();

  // Step 25: Click on "Attiéké poisson 304"
  // Playwright: page.locator('img[alt=\'Attiéké poisson 304\']')
  const el_25 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//img[@alt=\'Attiéké poisson 304\']') },
    { label: 'CSS (primary)', loc: page.locator('img[alt=\'Attiéké poisson 304\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//img)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('img:nth-of-type(1)') }
  ], 'Click on "Attiéké poisson 304"');
  await el_25.click();

  // Step 26: Scroll up
  // Playwright: page.locator('img[alt=\'Attiéké poisson 304\']')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 27: Click on "Retour au catalogue"
  // Playwright: page.locator('a')
  const el_27 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[contains(text(),\'Retour au catalogue\')]') },
    { label: 'CSS (primary)', loc: page.locator('a') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Retour au catalogue\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Retour au catalogue"');
  await el_27.click();

  // Step 28: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 29: Click on "Plats principaux"
  // Playwright: page.locator('.cat-filter__chip.is-active')
  const el_29 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Plats principaux\']') },
    { label: 'CSS (primary)', loc: page.locator('.cat-filter__chip.is-active') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Plats principaux"');
  await el_29.click();

  // Step 30: Scroll up
  // Playwright: page.locator('button')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 31: Click on "Mes commandes"
  // Playwright: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(3) > div:nth-child(1) > a:nth-child(1)')
  const el_31 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@aria-label=\'Mes commandes\']//a[@class=\'p-menuitem-link\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(3) > div:nth-child(1) > a:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[5]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Mes commandes\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Mes commandes"');
  await el_31.click();

  // Step 32: Click on "Admin"
  // Playwright: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(4) > div:nth-child(1) > a:nth-child(1)')
  const el_32 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@aria-label=\'Admin\']//a[@class=\'p-menuitem-link\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(4) > div:nth-child(1) > a:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[6]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Admin\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Admin"');
  await el_32.click();

  // Step 33: Scroll down
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 34: Scroll up
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 35: Click on "Administratrice"
  // Playwright: page.locator('.vyns-user__name')
  const el_35 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//span[@class=\'vyns-user__name\']') },
    { label: 'CSS (primary)', loc: page.locator('.vyns-user__name') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//span)[14]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//span[normalize-space()=\'Administratrice\']') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(1)') }
  ], 'Click on "Administratrice"');
  await el_35.click();

  // Step 36: Click on "Déconnexion"
  // Playwright: page.locator('a[aria-label=\'Déconnexion\']')
  const el_36 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[@aria-label=\'Déconnexion\']') },
    { label: 'CSS (primary)', loc: page.locator('a[aria-label=\'Déconnexion\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[30]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Déconnexion\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Déconnexion"');
  await el_36.click();

  // Step 37: Enter "ddebao911@gmail.com" into "vous@exemple.com"
  // Playwright: page.locator('input[placeholder=\'vous@exemple.com\']')
  const el_37 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@placeholder=\'vous@exemple.com\']') },
    { label: 'CSS (primary)', loc: page.locator('input[placeholder=\'vous@exemple.com\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "ddebao911@gmail.com" into "vous@exemple.com"');
  await el_37.fill(`ddebao911@gmail.com`);

  // Step 38: Enter "******" into "Votre mot de passe"
  // Playwright: page.locator('input[placeholder=\'Votre mot de passe\']')
  const el_38 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@placeholder=\'Votre mot de passe\']') },
    { label: 'CSS (primary)', loc: page.locator('input[placeholder=\'Votre mot de passe\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "******" into "Votre mot de passe"');
  await el_38.fill(`******`);

  // Step 39: Click on "Se connecter"
  // Playwright: page.locator('button[aria-label=\'Se connecter\']')
  const el_39 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Se connecter\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Se connecter\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[4]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Se connecter\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Se connecter"');
  await el_39.click();

  // Step 40: Click on "Mes commandes"
  // Playwright: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(3) > div:nth-child(1) > a:nth-child(1)')
  const el_40 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@aria-label=\'Mes commandes\']//a[@class=\'p-menuitem-link\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(3) > div:nth-child(1) > a:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[5]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Mes commandes\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Mes commandes"');
  await el_40.click();

  // Step 41: Scroll down
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 42: Scroll up
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 43: Click on "Catalogue"
  // Playwright: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(2) > div:nth-child(1) > a:nth-child(1)')
  const el_43 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//li[@aria-label=\'Catalogue\']//a[@class=\'p-menuitem-link\']') },
    { label: 'CSS (primary)', loc: page.locator('body > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(3) > li:nth-child(2) > div:nth-child(1) > a:nth-child(1)') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[4]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Catalogue\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Catalogue"');
  await el_43.click();

  // Step 44: Scroll down
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 45: Click on "Grillades & braisés"
  // Playwright: page.locator('.cat-filter__chip.is-active')
  const el_45 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Grillades & braisés\']') },
    { label: 'CSS (primary)', loc: page.locator('.cat-filter__chip.is-active') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[6]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(3)') }
  ], 'Click on "Grillades & braisés"');
  await el_45.click();

  // Step 46: Click on "Ajouté ✓"
  // Playwright: page.locator('button[aria-label=\'Ajouté ✓\']')
  const el_46 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Ajouté ✓\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Ajouté ✓\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[13]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Ajouté ✓\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Ajouté ✓"');
  await el_46.click();

  // Step 47: Click on "1"
  // Playwright: page.locator('.vyns-cart-badge')
  const el_47 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//span[@class=\'vyns-cart-badge\']') },
    { label: 'CSS (primary)', loc: page.locator('.vyns-cart-badge') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//span)[10]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//span[normalize-space()=\'1\']') },
    { label: 'nth-of-type CSS', loc: page.locator('span:nth-of-type(1)') }
  ], 'Click on "1"');
  await el_47.click();

  // Step 48: Scroll up
  // Playwright: page.locator('span')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 49: Click on "Haricots rouges 14147 FCFA / unité47 FCFA"
  // Playwright: page.locator('.p-inputnumber-button.p-inputnumber-button-down.p-button.p-button-icon-only.p-component')
  const el_49 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@class=\'p-inputnumber-button p-inputnumber-button-down p-button p-button-icon-only p-component\']') },
    { label: 'CSS (primary)', loc: page.locator('.p-inputnumber-button.p-inputnumber-button-down.p-button.p-button-icon-only.p-component') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(2)') }
  ], 'Click on "Haricots rouges 14147 FCFA / unité47 FCFA"');
  await el_49.click();

  // Step 50: Click on "Haricots rouges 14147 FCFA / unité94 FCFA"
  // Playwright: page.locator('.p-inputnumber-button.p-inputnumber-button-up.p-button.p-button-icon-only.p-component')
  const el_50 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@class=\'p-inputnumber-button p-inputnumber-button-up p-button p-button-icon-only p-component\']') },
    { label: 'CSS (primary)', loc: page.locator('.p-inputnumber-button.p-inputnumber-button-up.p-button.p-button-icon-only.p-component') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Haricots rouges 14147 FCFA / unité94 FCFA"');
  await el_50.click();

  // Step 51: Click on "Valider la commande"
  // Playwright: page.locator('button[aria-label=\'Valider la commande\']')
  const el_51 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Valider la commande\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Valider la commande\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[6]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Valider la commande\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Valider la commande"');
  await el_51.click();

  // Step 52: Click on "Confirmer la commande"
  // Playwright: page.locator('button[aria-label=\'Confirmer la commande\']')
  const el_52 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Confirmer la commande\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Confirmer la commande\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[3]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Confirmer la commande\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Confirmer la commande"');
  await el_52.click();

  // Step 53: Click on "Continuer mes achats"
  // Playwright: page.locator('button[aria-label=\'Continuer mes achats\']')
  const el_53 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[@aria-label=\'Continuer mes achats\']') },
    { label: 'CSS (primary)', loc: page.locator('button[aria-label=\'Continuer mes achats\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[4]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//button[normalize-space()=\'Continuer mes achats\']') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Continuer mes achats"');
  await el_53.click();

  // Step 54: Scroll down
  // Playwright: page.locator('button[aria-label=\'Continuer mes achats\']')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 55: Click on "Gâteaux événementiels"
  // Playwright: page.locator('.cat-filter__chip.is-active')
  const el_55 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Gâteaux événementiels\']') },
    { label: 'CSS (primary)', loc: page.locator('.cat-filter__chip.is-active') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[11]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(4)') }
  ], 'Click on "Gâteaux événementiels"');
  await el_55.click();

  // Step 56: Scroll up
  // Playwright: page.locator('button')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 57: Click on "Viennoiseries"
  // Playwright: page.locator('a[href=\'/catalogue?cat=Viennoiseries\']')
  const el_57 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Viennoiseries\']') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'/catalogue?cat=Viennoiseries\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[21]') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Viennoiseries"');
  await el_57.click();

  // Step 58: Scroll down
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 59: Click on "Cuisine & traiteur"
  // Playwright: page.locator('a[href=\'/catalogue?univers=Cuisine\']')
  const el_59 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[normalize-space()=\'Cuisine & traiteur\']') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'/catalogue?univers=Cuisine\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[27]') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Cuisine & traiteur"');
  await el_59.click();

  // Step 60: Scroll up
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 61: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 62: Click on "Mes commandes"
  // Playwright: page.locator('a[href=\'/mes-commandes\']')
  const el_62 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//a[@href=\'/mes-commandes\']') },
    { label: 'CSS (primary)', loc: page.locator('a[href=\'/mes-commandes\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//a)[24]') },
    { label: 'Text-based XPath', loc: page.locator('xpath=//a[normalize-space()=\'Mes commandes\']') },
    { label: 'nth-of-type CSS', loc: page.locator('a:nth-of-type(1)') }
  ], 'Click on "Mes commandes"');
  await el_62.click();

  // Step 63: Scroll up
  // Playwright: page.locator('a')
  await page.evaluate(() => window.scrollBy(0, -400));

  // Step 64: Scroll down
  await page.evaluate(() => window.scrollBy(0, 400));

  // Step 65: Scroll up
  await page.evaluate(() => window.scrollBy(0, -400));

  console.log('\n✓ All 65 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});